In [3]:
my_list = [1,2,3]

In [12]:
my_list

[1, 2, 3]

In [6]:
import numpy as np

In [10]:
arr = np.array(my_list)

In [11]:
arr

array([1, 2, 3])

In [14]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.linspace(0,100,10) #evenly distributed between a range with a number of points

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.12753816, 0.50368212, 0.5332729 , 0.80109146, 0.8233011 ])

In [36]:
np.random.rand(5,5)

array([[0.1297573 , 0.28309756, 0.09994359, 0.38709254, 0.60771451],
       [0.68054034, 0.89237261, 0.32368879, 0.6437666 , 0.1053828 ],
       [0.16669397, 0.94588612, 0.37187892, 0.21985122, 0.90912535],
       [0.37854279, 0.00818437, 0.93772083, 0.92312643, 0.11495903],
       [0.9545668 , 0.96221519, 0.6928119 , 0.46153229, 0.33014884]])

In [38]:
np.random.randn(6)

array([ 0.58771721,  0.74478462,  0.02828668, -0.21510698, -0.45946797,
       -0.29880765])

In [57]:
np.random.randint(1,101,10)

array([68, 84, 40, 51, 98, 76, 75, 34, 10,  2])